services:

  portal-municipal-mao:
    build: ./portal-municipio-mao
    container_name: portal-municipal-mao
    restart: no
    volumes:
      - ./novo7/credentials.json:/app/credentials.json:ro
      - ./logs:/app/logs
    environment:
      - TZ=America/Manaus
      - SUPABASE_DB_HOST=supabase-db
      - SUPABASE_DB_PORT=5432
      - SUPABASE_DB_NAME=postgres
      - SUPABASE_DB_USER=postgres
      - SUPABASE_DB_PASSWORD=HKcSH_yTEsQ42cdEvhruQ9kNbrN54U4WfiLKDXD-Tf0
    networks:
      - portal_default
      - supabase_default

  aristoteles:
    build: ./aristoteles
    container_name: portal-aristoteles
    restart: no
    volumes:
      - ./aristoteles/pdfs:/app/pdfs
      - ./logs:/app/logs
    environment:
      - TZ=America/Manaus
      - SUPABASE_DB_HOST=supabase-db
      - SUPABASE_DB_PORT=5432
      - SUPABASE_DB_NAME=postgres
      - SUPABASE_DB_USER=postgres
      - SUPABASE_DB_PASSWORD=HKcSH_yTEsQ42cdEvhruQ9kNbrN54U4WfiLKDXD-Tf0
      - LOG_FILE=/app/logs/aristoteles.log
    networks:
      - portal_default
      - supabase_default

  cleaner:
    build: ./cleaner
    container_name: portal-cleaner
    restart: no
    networks:
      - portal_default
      - supabase_default
    environment:
      - TZ=America/Manaus

  cleaner-estado-am:
    build: ./cleaner-estado-am
    container_name: portal-cleaner-estado-am
    restart: no
    networks:
      - portal_default
      - supabase_default
    environment:
      - TZ=America/Manaus

  portal-estado-ms:
    build: ./portal-estado-ms
    container_name: portal-estado-ms
    restart: no
    volumes:
      - ./novo7/credentials.json:/app/credentials.json:ro
      - ./logs:/app/logs
    environment:
      - TZ=America/Campo_Grande
      - SUPABASE_DB_HOST=supabase-db
      - SUPABASE_DB_PORT=5432
      - SUPABASE_DB_NAME=postgres
      - SUPABASE_DB_USER=postgres
      - SUPABASE_DB_PASSWORD=HKcSH_yTEsQ42cdEvhruQ9kNbrN54U4WfiLKDXD-Tf0
    networks:
      - portal_default
      - supabase_default

  portal-estado-ro:
    build: ./portal-estado-ro
    container_name: portal-estado-ro
    restart: no
    volumes:
      - ./novo7/credentials.json:/app/credentials.json:ro
      - ./logs:/app/logs
    environment:
      - TZ=America/Porto_Velho
      - SUPABASE_DB_HOST=supabase-db
      - SUPABASE_DB_PORT=5432
      - SUPABASE_DB_NAME=postgres
      - SUPABASE_DB_USER=postgres
      - SUPABASE_DB_PASSWORD=HKcSH_yTEsQ42cdEvhruQ9kNbrN54U4WfiLKDXD-Tf0
    networks:
      - portal_default
      - supabase_default

  portal-estado-am:
    build: ./portal-estado-am
    container_name: portal-estado-am
    restart: no
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=America/Manaus
      - SUPABASE_DB_HOST=supabase-db
      - SUPABASE_DB_PORT=5432
      - SUPABASE_DB_NAME=postgres
      - SUPABASE_DB_USER=postgres
      - SUPABASE_DB_PASSWORD=HKcSH_yTEsQ42cdEvhruQ9kNbrN54U4WfiLKDXD-Tf0
    networks:
      - portal_default
      - supabase_default

  api:
    build: ./api
    container_name: portal-api
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      - TZ=America/Manaus
      - DB_HOST=supabase-db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=HKcSH_yTEsQ42cdEvhruQ9kNbrN54U4WfiLKDXD-Tf0
      - API_KEY_PORTAL_MUNICIPAL_MANAUS=aris-22386d82643aa6e36b12688a7175698d
      - API_KEY_PORTAL_ESTADO_AM=estam-52394a9ff66f976ee2ab097a6844a7a4
      - API_KEY_PORTAL_ESTADO_MS=estms-7f3c91a2b84d5e6f019c237ab8d4e15f
      - API_KEY_PORTAL_ESTADO_RO=estro-3b8f72c1d94a6e520f7b183cd5a9e04d
    networks:
      - portal_default
      - supabase_default

networks:
  portal_default:
    driver: bridge
  supabase_default:
    external: true
