FROM python:3.12-slim
WORKDIR /app
RUN pip install --no-cache-dir psycopg2-binary
COPY cleaner_municipio_pvh.py .
COPY cleaner_municipio_pvh_config.json .
CMD ["python3", "-u", "cleaner_municipio_pvh.py"]
